### ISSUE TITLE
How to set initialization ZIndex？

### ISSUE THREAD

**Issue by qvefofo** [Gikoskos/react-win32dialog#3]

**Comment by Gikoskos** [comment]
The ZIndexes are handled by the Window manager. There's no way to set your own z-index in each individual window because you might break the order of the windows (some z-indexes might end up in conflict). You could make windows that don't depend on a window manager and act on their own, by removing all register/unregister calls to Win32Dialog.windowManager from the Win32Dialog class, but then your window won't react to mouse events because only the windowManager captures those.
